services:
  postgres:
    image: postgres:16
    container_name: postgres_dev
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hydrodb-dev
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - hydro-network

  redis:
    image: redis:7-alpine
    container_name: redis_dev
    command: redis-server --loglevel verbose
    ports:
      - '6379:6379'
    volumes:
      - cache:/data
    networks:
      - hydro-network

  mosquitto:
    build:
      context: ./mosquitto
    container_name: mosquitto_dev
    ports:
      - '1883:1883'
    networks:
      - hydro-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq_dev
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - hydro-network

volumes:
  pgdata:
  cache:

networks:
  hydro-network:
    driver: bridge