allow_anonymous = false

auth {
    # Drop unauthenticated requests immediately
    no_match = deny
    deny_action = disconnect

    # Static rules, evaluated before HTTP webhook checks
      rules = [
          # Allow admin to read system topics
          {"permit": "allow", "username": "admin", "topic": "$SYS/#", "action": "subscribe"},

          # Explicitly DENY all other clients from subscribing to system topics
          {"permit": "deny", "topic": "$SYS/#", "action": "subscribe"}
      ]

    # Use HTTP webhooks for authentication and ACL checks
    http_auth = {
        # On connection attempt:
        auth_req {
            url = "http://host.docker.internal:8080/v1/internal/mqtt/auth"
            method = "POST"
            headers.content-type = "application/json"
            params = {
                username = "%u",
                password = "%P",
                clientid = "%c"
            }
        }

        acl_req {
            url = "http://host.docker.internal:8080/v1/internal/mqtt/acl"
            method = "POST"
            headers.content-type = "application/json"
            params = {
                username = "%u",
                clientid = "%c",
                topic = "%t",
                action = "%A",
                password = "%P"
            }
        }
    }
}