log {
    to = [file, console]
    level = debug
    dir = "/var/log"
    file = "nanomq.log"
    rotation  = {
        size = 10MB
        count = 5
    }
}
listeners.tcp {
  bind = "0.0.0.0:1883"
}
listeners.ssl {
    default {
        bind = "0.0.0.0:8883"
        certfile = "/etc/nanomq/certs/certificate.crt"
        keyfile = "/etc/nanomq/certs/privatekey.key"
        cacertfile = "/etc/nanomq/certs/certificate.crt"
        verify_peer = false
        fail_if_no_peer_cert = false
    }
}
auth {
    allow_anonymous = false
    no_match = deny
    deny_action = disconnect
    plugins.client_status = false

    jwt {
        public_key = "/etc/mqtt_public_key.pem"
        algorithm = "RS512"
    }

    http_auth = {
        auth_req {
            url = "http://api:8080/v1/internal/mqtt/auth"
            method = "POST"
            headers.content-type = "application/json"
            params = {
                username = "%u",
                password = "%P",
                clientid = "%c"
            }
        }

        acl_req {
            url = "http://api:8080/v1/internal/mqtt/acl"
            method = "POST"
            headers.content-type = "application/json"
            params = {
                username = "%u",
                clientid = "%c",
                topic = "%t",
                action = "%A",
                password = "%P"
            }
        }
    }
}