spring.config.import=optional:file:../.env[.properties],optional:file:.env[.properties]
# JWT settings
jwt.expiration-ms=3600000
jwt.refresh-expiration-ms=86400000
mqtt.jwt.expiration-ms=300000
# SwaggerUI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
