spring.config.import=optional:file:../.env[.properties],optional:file:.env[.properties]
# Secrets (provided by Vault in prod)
spring.cloud.vault.enabled=false
jwt.secret=XL1pqJURj0rFbdWXiHCwD0tdFlNy/hhDVLmjEl3GoKRtkjfqUYh7j7MAlsNCch0Ew6ParzBnuAt3E4bODCj5Eg==
recovery.secret=CH45JyhYaMp/wWDD43DIfQ1RgFyGIo3IjOVkrugEw+uNmVHsODwe6bhyYxlomYta45x16FKmjmjIR8uCHuT2/w==
device.secret=CH45JyhYaMp0Ew6ParzBnuAt3E3DIfQ1RgFyGIo3IjOVkrugEw+uFlNy/hhDVLmjEYta45x16F0EarzBnuAt3Ew==
# Database settings
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://192.168.1.214:5433/hydrodb
spring.datasource.username=admin
spring.datasource.password=supersecret
spring.jpa.hibernate.ddl-auto=update
# Redis settings
spring.data.redis.host=redis
spring.data.redis.port=6379
spring.data.redis.password=secret
spring.cache.redis.time-to-live=10m
# Proxy awareness
server.forward-headers-strategy=framework
# CORS (Vite)
cors.allowed-origins=http://192.168.1.214:5173
#management.endpoints.health.show-details=never
# Logging
logging.level.org.springframework=ERROR
