spring.config.import=optional:file:../.env[.properties],optional:file:.env[.properties]
# Secrets (provided by Vault in prod)
spring.cloud.vault.enabled=false
jwt.secret=XL1pqJURj0rFbdWXiHCwD0tdFlNy/hhDVLmjEl3GoKRtkjfqUYh7j7MAlsNCch0Ew6ParzBnuAt3E4bODCj5Eg==
mqtt.jwt.secret=XL1pqJURj0rFbdWXiHCwD0tdFlNy/hhDVLmjEl3GoKRtkjfqUYh7j7MAlsNCch0Ew6ParzBnuAt3E4bODCj5Eg==
recovery.secret=CH45JyhYaMp/wWDD43DIfQ1RgFyGIo3IjOVkrugEw+uNmVHsODwe6bhyYxlomYta45x16FKmjmjIR8uCHuT2/w==
device.secret=CH45JyhYaMp0Ew6ParzBnuAt3E3DIfQ1RgFyGIo3IjOVkrugEw+uFlNy/hhDVLmjEYta45x16F0EarzBnuAt3Ew==
# Database settings
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5433/hydrotestdb
spring.datasource.username=admin
spring.datasource.password=supersecret
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
# Redis settings
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=supersecret
spring.data.redis.ssl.enabled=false
# Cache settings
spring.cache.type=redis
# Hibernate settings
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.physical_naming_strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
spring.jpa.properties.hibernate.implicit_naming_strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
# RabbitMQ settings
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=myuser
spring.rabbitmq.password=supersecret
# Modulith settings
spring.modulith.events.republish-outstanding-events-on-restart=true
spring.modulith.events.jdbc.schema-initialization.enabled=true
# CORS (Vite)
cors.allowed-origins=http://127.0.0.1:5173
# Logging
logging.level.org.springframework.web=DEBUG
logging.level.dev.ivfrost.hydro_backend=DEBUG