spring.config.import=optional:file:../.env[.properties],optional:file:.env[.properties]
server.port=8080
# Secrets (provided by Vault in prod)
spring.cloud.vault.enabled=false
jwt.secret=XL1pqJURj0rFbdWXiHCwD0tdFlNy/hhDVLmjEl3GoKRtkjfqUYh7j7MAlsNCch0Ew6ParzBnuAt3E4bODCj5Eg==
recovery.secret=19rWp+tewwkvUJu1QGXXQ049OgaACoZi+y7UVNkGYpU=
device.secret=yr7WkTwDYdR4FmTihsUvTRfrWi9C2IPqBUNGj98l7IQ=
# JWT settings
jwt.refresh.expiration.ms=2592000000
jwt.access.expiration.ms=900000
# MQTT JWT settings
mqtt.jwt.expiration.ms=600000
mqtt.jwt.private.key.path=./mqtt_private_key.der
# Database settings
spring.datasource.url=jdbc:postgresql://localhost:5432/hydrodb-dev
spring.datasource.username=admin
spring.datasource.password=password
spring.jpa.show-sql=true
spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
# Redis settings
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.ssl.enabled=false
spring.cache.type=redis
# Hibernate settings
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.physical_naming_strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
spring.jpa.properties.hibernate.implicit_naming_strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
# RabbitMQ settings
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=password
# Modulith settings
spring.modulith.events.republish-outstanding-events-on-restart=true
spring.modulith.events.jdbc.schema-initialization.enabled=true
# CORS (Vite)
cors.allowed-origins=http://127.0.0.1:5173,http://localhost:5173
# Logging
logging.level.org.springframework.web=DEBUG
logging.level.dev.ivfrost.hydro_backend=DEBUG
