listener 1883
allow_anonymous false

auth_plugin /usr/lib/mosquitto/libmosquitto_jwt_auth.so
auth_opt_jwt_alg RS256
auth_opt_jwt_sec_file /mosquitto/config/public_key.pem
auth_opt_jwt_iss HydroAPI
auth_opt_jwt_validate_exp true
auth_opt_jwt_validate_sub_match_username false