CREATE TABLE users (
                       id bigint NOT NULL,
                       address text,
                       created_at timestamp(6) with time zone NOT NULL,
                       deleted_at timestamp(6) with time zone,
                       email character varying(50) NOT NULL,
                       full_name character varying(40) NOT NULL,
                       is_enabled boolean NOT NULL,
                       notes text,
                       password character varying(255) NOT NULL,
                       phone_number character varying(20),
                       profile_pic character varying(255),
                       settings text,
                       updated_at timestamp(6) with time zone NOT NULL,
                       username character varying(20) NOT NULL
);

ALTER TABLE users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE user_roles (
                            user_id bigint NOT NULL,
                            role character varying(255) NOT NULL,
                            CONSTRAINT user_roles_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying])::text[])))
);

CREATE TABLE devices (
                         id bigint NOT NULL,
                         created_at timestamp(6) with time zone NOT NULL,
                         display_order bigint,
                         firmware character varying(20) NOT NULL,
                         friendly_name character varying(40),
                         ip character varying(15),
                         key character varying(255) NOT NULL,
                         last_seen timestamp(6) with time zone,
                         linked_at timestamp(6) with time zone,
                         location character varying(255),
                         mac_address character varying(17) NOT NULL,
                         secret character varying(255),
                         technical_name character varying(40) NOT NULL,
                         updated_at timestamp(6) with time zone NOT NULL,
                         user_id bigint
);

ALTER TABLE devices ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME devices_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE tokens (
                        id bigint NOT NULL,
                        expiry_date timestamp(6) without time zone,
                        type character varying(20) NOT NULL,
                        user_id bigint NOT NULL,
                        value character varying(255) NOT NULL,
                        CONSTRAINT tokens_type_check CHECK (((type)::text = ANY ((ARRAY['AUTH_RECOVERY_CODE'::character varying, 'AUTH_ACCESS_TOKEN'::character varying, 'AUTH_REFRESH_TOKEN'::character varying, 'MQTT_TOKEN'::character varying, 'DEVICE_MQTT_TOKEN'::character varying])::text[])))
);

ALTER TABLE tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE event_publication (
                                   id uuid NOT NULL,
                                   listener_id text NOT NULL,
                                   event_type text NOT NULL,
                                   serialized_event text NOT NULL,
                                   publication_date timestamp with time zone NOT NULL,
                                   completion_date timestamp with time zone,
                                   status text,
                                   completion_attempts integer,
                                   last_resubmission_date timestamp with time zone
);

-- Primary keys
ALTER TABLE ONLY users ADD CONSTRAINT users_pkey PRIMARY KEY (id);
ALTER TABLE ONLY devices ADD CONSTRAINT devices_pkey PRIMARY KEY (id);
ALTER TABLE ONLY tokens ADD CONSTRAINT tokens_pkey PRIMARY KEY (id);
ALTER TABLE ONLY event_publication ADD CONSTRAINT event_publication_pkey PRIMARY KEY (id);

-- Unique constraints
ALTER TABLE ONLY users ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);
ALTER TABLE ONLY users ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);
ALTER TABLE ONLY devices ADD CONSTRAINT ukbfdu66xgk53rkn5023ce70rvw UNIQUE (mac_address);
ALTER TABLE ONLY devices ADD CONSTRAINT ukjkf98jkne5dpygw3ttsp983a0 UNIQUE (key);

-- Indexes
CREATE INDEX event_publication_by_completion_date_idx ON event_publication USING btree (completion_date);
CREATE INDEX event_publication_serialized_event_hash_idx ON event_publication USING hash (serialized_event);

-- Foreign keys
ALTER TABLE ONLY user_roles ADD CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id) REFERENCES users(id);