CREATE TABLE devices
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY   NOT NULL,
    key                 VARCHAR(255)                              NOT NULL,
    mac_address         VARCHAR(17)                                NOT NULL,
    friendly_name       VARCHAR(40),
    location_coordinates VARCHAR(255),
    location_label      VARCHAR(255),
    firmware            VARCHAR(20)                                NOT NULL,
    technical_name       VARCHAR(40)                                NOT NULL,
    secret               VARCHAR(255),
    description          VARCHAR(255),
    ip                   VARCHAR(15),
    image_url            VARCHAR(2048),
    created_at           TIMESTAMP(6) WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at           TIMESTAMP(6) WITH TIME ZONE DEFAULT NOW() NOT NULL,
    linked_at            TIMESTAMP(6) WITH TIME ZONE,
    user_id              BIGINT,
    display_order        BIGINT,
    last_ota_update_id   BIGINT,
    CONSTRAINT pk_devices PRIMARY KEY (id)
);

CREATE TABLE tokens
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    value       VARCHAR(255)                            NOT NULL,
    type        VARCHAR(20)                             NOT NULL,
    expiry_date TIMESTAMP WITH TIME ZONE,
    user_id     BIGINT                                  NOT NULL,
    CONSTRAINT pk_tokens PRIMARY KEY (id)
);

CREATE TABLE user_roles
(
    user_id BIGINT       NOT NULL,
    role    VARCHAR(255) NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role)
);

CREATE TABLE users
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username     VARCHAR(20)                             NOT NULL,
    password     VARCHAR(255)                            NOT NULL,
    full_name    VARCHAR(40)                             NOT NULL,
    email        VARCHAR(50)                             NOT NULL,
    image_url    VARCHAR(255),
    phone_number VARCHAR(20),
    address      TEXT,
    created_at   TIMESTAMP WITH TIME ZONE DEFAULT NOW()  NOT NULL,
    updated_at   TIMESTAMP WITH TIME ZONE DEFAULT NOW()  NOT NULL,
    deleted_at   TIMESTAMP WITH TIME ZONE,
    settings     TEXT,
    notes        TEXT,
    is_enabled   BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE ota_updates
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY   NOT NULL,
    version        VARCHAR(255)                              NOT NULL,
    technical_name VARCHAR(40)                               NOT NULL,
    object_key     VARCHAR(512)                              NOT NULL,
    sha256         VARCHAR(64)                               NOT NULL,
    size_bytes     BIGINT                                    NOT NULL,
    force_install  BOOLEAN                  DEFAULT FALSE    NOT NULL,
    created_at     TIMESTAMP(6) WITH TIME ZONE DEFAULT NOW() NOT NULL,
    CONSTRAINT pk_ota_updates PRIMARY KEY (id)
);

CREATE SEQUENCE IF NOT EXISTS schedule_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE schedule
(
    id          BIGINT   NOT NULL,
    day_of_week SMALLINT NOT NULL,
    device_id   BIGINT   NOT NULL,
    CONSTRAINT pk_schedule PRIMARY KEY (id)
);

CREATE TABLE time_window
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pin                     INTEGER                                 NOT NULL,
    start_type              VARCHAR(255)                            NOT NULL,
    fixed_time              time(6) WITHOUT TIME ZONE,
    linked_pin              INTEGER,
    offset_minutes          INTEGER,
    duration_minutes        INTEGER                                 NOT NULL,
    schedule_id             BIGINT                                  NOT NULL,
    linked_reference_point  VARCHAR(255),
    CONSTRAINT pk_timewindow PRIMARY KEY (id)
);

CREATE SEQUENCE IF NOT EXISTS pins_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE pins
(
    id         BIGINT       NOT NULL,
    pin_number INTEGER      NOT NULL,
    mode       VARCHAR(255) NOT NULL,
    label      VARCHAR(255),
    device_id  BIGINT       NOT NULL,
    CONSTRAINT pk_pins PRIMARY KEY (id)
);

-- Unique constraints
ALTER TABLE devices ADD CONSTRAINT uc_devices_key UNIQUE (key);
ALTER TABLE devices ADD CONSTRAINT uc_devices_mac_address UNIQUE (mac_address);
ALTER TABLE devices ADD CONSTRAINT uc_devices_secret UNIQUE (secret);
ALTER TABLE tokens ADD CONSTRAINT uc_tokens_value UNIQUE (value);
ALTER TABLE users ADD CONSTRAINT uc_users_email UNIQUE (email);
ALTER TABLE users ADD CONSTRAINT uc_users_username UNIQUE (username);
ALTER TABLE schedule ADD CONSTRAINT uq_schedule_device_day UNIQUE (device_id, day_of_week);
ALTER TABLE pins ADD CONSTRAINT uq_pin_device_number UNIQUE (device_id, pin_number);

-- Indexes
CREATE INDEX idx_tokens_user_id ON tokens (user_id);
CREATE INDEX idx_devices_user_id ON devices (user_id);
CREATE INDEX idx_ota_updates_technical_name ON ota_updates (technical_name, created_at DESC);

-- Foreign keys
ALTER TABLE user_roles ADD CONSTRAINT FK_USER_ROLES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE schedule ADD CONSTRAINT FK_SCHEDULE_ON_DEVICE FOREIGN KEY (device_id) REFERENCES devices (id);
ALTER TABLE time_window ADD CONSTRAINT FK_TIMEWINDOW_ON_SCHEDULE FOREIGN KEY (schedule_id) REFERENCES schedule (id);
ALTER TABLE pins ADD CONSTRAINT FK_PINS_ON_DEVICE FOREIGN KEY (device_id) REFERENCES devices (id);