CREATE TABLE devices
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    key            VARCHAR(255)                            NOT NULL,
    mac_address    VARCHAR(17)                             NOT NULL,
    friendly_name  VARCHAR(40),
    location       VARCHAR(255),
    firmware       VARCHAR(20)                             NOT NULL,
    technical_name VARCHAR(40)                             NOT NULL,
    secret         VARCHAR(255),
    description    VARCHAR(255),
    ip             VARCHAR(15),
    image_url      VARCHAR(255),
    created_at     TIMESTAMP(6) WITH TIME ZONE              NOT NULL,
    updated_at     TIMESTAMP(6) WITH TIME ZONE              NOT NULL,
    linked_at      TIMESTAMP(6) WITH TIME ZONE,
    last_seen      TIMESTAMP(6) WITH TIME ZONE,
    user_id        BIGINT, -- intentionally not a FK to avoid tight coupling (modulith)
    display_order  BIGINT,
    CONSTRAINT pk_devices PRIMARY KEY (id)
);

CREATE TABLE tokens
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    value       VARCHAR(255)                            NOT NULL,
    type        VARCHAR(20)                             NOT NULL,
    expiry_date TIMESTAMP(6) WITH TIME ZONE,
    user_id     BIGINT                                  NOT NULL, -- intentionally not a FK to avoid tight coupling (modulith)
    CONSTRAINT pk_tokens PRIMARY KEY (id)
);

CREATE TABLE user_roles
(
    user_id BIGINT       NOT NULL,
    role    VARCHAR(255) NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role)
);

CREATE TABLE users
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username     VARCHAR(20)                             NOT NULL,
    password     VARCHAR(255)                            NOT NULL,
    full_name    VARCHAR(40)                             NOT NULL,
    email        VARCHAR(50)                             NOT NULL,
    profile_pic  VARCHAR(255),
    phone_number VARCHAR(20),
    address      TEXT,
    created_at   TIMESTAMP(6) WITH TIME ZONE              NOT NULL,
    updated_at   TIMESTAMP(6) WITH TIME ZONE              NOT NULL,
    deleted_at   TIMESTAMP(6) WITH TIME ZONE,
    settings     TEXT,
    notes        TEXT,
    is_enabled   BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE devices
    ADD CONSTRAINT uc_devices_key UNIQUE (key);

ALTER TABLE devices
    ADD CONSTRAINT uc_devices_mac_address UNIQUE (mac_address);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_user_roles_on_user FOREIGN KEY (user_id) REFERENCES users (id);