CREATE TABLE ota_updates
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY   NOT NULL,
    version        VARCHAR(255)                              NOT NULL,
    technical_name VARCHAR(40)                               NOT NULL,
    object_key     VARCHAR(512)                              NOT NULL,
    sha256         VARCHAR(64)                               NOT NULL,
    size_bytes     BIGINT                                    NOT NULL,
    force_install  BOOLEAN                  DEFAULT FALSE    NOT NULL,
    created_at     TIMESTAMP(6) WITH TIME ZONE DEFAULT NOW() NOT NULL,
    CONSTRAINT pk_ota_updates PRIMARY KEY (id)
);

CREATE INDEX idx_ota_updates_technical_name ON ota_updates (technical_name, created_at DESC);