CREATE SEQUENCE IF NOT EXISTS schedule_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE schedule
(
    id          BIGINT   NOT NULL,
    day_of_week SMALLINT NOT NULL,
    device_id   BIGINT   NOT NULL,
    CONSTRAINT pk_schedule PRIMARY KEY (id)
);

ALTER TABLE schedule ADD CONSTRAINT uq_schedule_device_day UNIQUE (device_id, day_of_week);

ALTER TABLE schedule
    ADD CONSTRAINT FK_SCHEDULE_ON_DEVICE FOREIGN KEY (device_id) REFERENCES devices (id);

CREATE TABLE time_window
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pin              INTEGER                                 NOT NULL,
    start_type       VARCHAR(255)                            NOT NULL,
    fixed_time       time(6) WITHOUT TIME ZONE,
    linked_pin       INTEGER,
    offset_minutes   INTEGER,
    duration_minutes INTEGER                                 NOT NULL,
    schedule_id      BIGINT                                  NOT NULL,
    CONSTRAINT pk_timewindow PRIMARY KEY (id)
);

ALTER TABLE time_window
    ADD CONSTRAINT FK_TIMEWINDOW_ON_SCHEDULE FOREIGN KEY (schedule_id) REFERENCES schedule (id);